from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph, Frame
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import os

def create_pdf(report_text, crop_name):
    os.makedirs("reports", exist_ok=True)
    file_path = f"reports/Farm_Advisory_{crop_name}.pdf"
    
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter
    
    # Colors
    primary = HexColor("#00C853")
    secondary = HexColor("#2979FF")
    text_color = HexColor("#1a1c1e")
    bg_color = HexColor("#f4f6f8")
    
    # Draw Background Setup
    c.setFillColor(bg_color)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    # Draw Header Background
    c.setFillColor(primary)
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    # Draw Header Text
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 50, "AI Advisory Report")
    
    c.setFont("Helvetica", 14)
    c.drawString(40, height - 75, f"Crop: {crop_name} | Generated by HaveCrops AI")
    
    # Body Styles
    styles = getSampleStyleSheet()
    h1_style = ParagraphStyle(
        "H1", parent=styles["Heading1"], fontSize=16, textColor=secondary, spaceAfter=10, fontName="Helvetica-Bold"
    )
    body_style = ParagraphStyle(
        "BodyText", parent=styles["Normal"], fontSize=11, textColor=text_color, spaceAfter=8, leading=14
    )
    
    y = height - 130
    c.setFillColor(text_color)
    
    # Parse and draw
    lines = report_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            y -= 10
            continue
            
        if line.startswith("#") or line.startswith("**"):
            c.setFont("Helvetica-Bold", 14)
            c.setFillColor(secondary)
            clean_line = line.replace("#", "").replace("**", "").strip()
            
            # Subtle section underline
            c.setStrokeColor(HexColor("#e0e0e0"))
            c.line(40, y - 5, width - 40, y - 5)
            
            c.drawString(40, y, clean_line)
            y -= 25
            c.setFillColor(text_color)
            c.setFont("Helvetica", 11)
        elif line.startswith("-") or line.startswith("*"):
            c.setFont("Helvetica", 11)
            clean_line = "• " + line[1:].replace("**", "").strip()
            wrapped = simpleSplit(clean_line, "Helvetica", 11, width - 100)
            for wl in wrapped:
                c.drawString(50, y, wl)
                y -= 15
        else:
            c.setFont("Helvetica", 11)
            wrapped = simpleSplit(line.replace("**", ""), "Helvetica", 11, width - 80)
            for wl in wrapped:
                c.drawString(40, y, wl)
                y -= 15
                
        if y < 50:
            c.showPage()
            c.setFillColor(bg_color)
            c.rect(0, 0, width, height, fill=1, stroke=0)
            c.setFillColor(text_color)
            y = height - 50
            
    # Footer
    c.setFillColor(HexColor("#9e9e9e"))
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, 30, "Disclaimer: This AI-generated report should not replace professional agronomic advice.")

    c.save()
    return file_path
